general.import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
  # "~/.config/alacritty/themes/tokyo-night.toml"
  # "~/.config/alacritty/themes/tokyo-night-storm.toml"
  # "~/.config/alacritty/themes/tokyonight_day.toml"
  # "~/.config/alacritty/themes/tokyonight_moon.toml"
  # "~/.config/alacritty/themes/tokyonight_night.toml"
  # "~/.config/alacritty/themes/tokyonight_storm.toml"
  "~/.config/alacritty/themes/cyberpunk-neon.toml"
]

[window]
decorations = "None"
opacity = 0.8

[window.padding]
x = 10
y = 10

[font]
size = 11.0

[font.normal]
family = "0xProto Nerd Font Mono"
style = "Regular"

[cursor.style]
shape = "Block"
blinking = "Always"

[selection]
save_to_clipboard = true

[terminal.shell]
program = "/usr/bin/bash"
